version: '3.3'

volumes:
  static_value:
  media_value:
  justice_db_data:

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - justice_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.env
    networks:
      - mynetwork      
    container_name: justice_bot_db

  backend:
    image: kotbarbarossa/justice_bot_backend:latest
    ports:
      - "8000:8000"    
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - mynetwork      
    container_name: justice_bot_backend

  bot:
    image: kotbarbarossa/justice_python_bot:latest
    restart: always
    depends_on:
      - backend    
    env_file:
      - ./.env
    networks:
      - mynetwork      
    container_name: justice_python_bot

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    networks:
      - mynetwork       
    container_name: justice_bot_nginx    

networks:
  mynetwork: